apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: gremio-client
        imagePullPolicy: Never
        env:
        - name: SERVER_HOST
          value: "socket-server-lb"  # Or use LoadBalancer IP
        - name: SERVER_PORT
          value: "80"

