kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
localAPIEndpoint:
  advertiseAddress: 192.168.13.13
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
clusterName: Gremio
networking:
  podSubnet: "192.168.0.0/16"  # Matches Calico
