apiVersion: v1
kind: Service
metadata:
  name: socket-server-lb
spec:
  clusterIP: 10.96.0.100
  type: NodePort
  selector:
    app: server
  ports:
    - port: 80
      targetPort: 9999
      nodePort: 32000
      protocol: UDP

